### ISSUE TITLE
Check fuels from TiCo smeltery

### ISSUE THREAD

**Issue by JasonMcRay** [JasonMcRay/Infitech-2-reloaded#1]
If there are any too much powerful fuel remove it, allow only those very close to lava heat

**Comment by ct-klein** [comment]
checked all things 'fuel' and while it accepts it as input it does not process anything.  tried all of the lava, and pahoehoe lava does not process.  only standard lava buckets, cells, can.

**Comment by JasonMcRay** [comment]
Generated a list of possible fuels and only accepts lava, nothing else.
