### ISSUE TITLE
IC2 ores generating normally

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/Infitech-2-reloaded#10]
As discussed in #beta-testing, added here just for tracking purposes...

What happens:
IC2 ores (copper, lead, tin and uranium) generating normally.

What you expected to happen:
IC2 ores to be disabled.

Modpack Version: Infitech 2 - Pre-loaded-0.0.1b

I have not modified the pack in any way.

This issue is happening on the CLIENT in SINGLE PLAYER.
I have not tested this on server, but I assume a server would be the same.

Log: N/A

**Comment by JasonMcRay** [comment]
Fixed in 0.0.2
