### ISSUE TITLE
Pam's salt ore generating normally

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/Infitech-2-reloaded#11]
As discussed on #beta-testing, added here for tracking purposes...

What happens:
Pam's salt ore is generating normally. When harvested it drops GT salt (dust) which provides easy access to GT salt without finding a GT salt vein.

What you expected to happen:
Pam's salt ore to be disabled in harvestcraft.cfg (B:enablesaltGeneration=false)

Modpack Version: Infitech 2 - Pre-loaded-0.0.1b

I have not modified the pack in any way.

This issue is happening on the CLIENT in SINGLE PLAYER.
I have not tested this on server, but I assume a server would do the same thing.

Log: N/A

**Comment by JasonMcRay** [comment]
Fixed in 0.0.2
