### ISSUE TITLE
component recipe imbalance

### ISSUE THREAD

**Issue by ct-klein** [JasonMcRay/Infitech-2-reloaded#13]
#### Issue Description:
Several different parts that do the same thing all at different tech levels.

#### Is the issue happening on server? Client? Both?
both

#### What happens:
Looking at some recipes that call for the IC2 advanced circuit or equivalent.  It will cycle thru 4 possible options.
Forestry - Integrated circuit board (requires epoxy circuit board)
GT - Processor Assembly MV power range
GT - Nano Processor EV power range
IC2 - Advanced Circuit LV power range (gold and redstone)

Guess which one I'm going to use.

#### What you expected to happen:
Just thinking something might need to be adjusted

#### Steps to reproduce (if aplicable):

1.
2.
3.
...

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):
0.0.2

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by JasonMcRay** [comment]
Removed assembler recipe for advanced circuit
