### ISSUE TITLE
Nuclearcraft: gregtech fuels for nuclear furnace do not work

### ISSUE THREAD

**Issue by ct-klein** [JasonMcRay/Infitech-2-reloaded#14]
#### Issue Description:
The nuclear furnace from Nuclearcraft is supposed to be able to accept uranium ingots/dust or thorium ingots/dust as fuel.  

#### Is the issue happening on server? Client? Both?
both

#### What happens:
the nuclear craft 'nuclear furnace' will not accept gregtech equlivant ingots/dust as fuel.

#### What you expected to happen:
oredict to allow them to be recognized?
Even in creative if I take the nuclearcraft ingots and drag them to my toolbar they get changed into gregtech ingots.

#### Steps to reproduce (if aplicable):
try to use any gregtech uranium/thorium in the furnace and it doesn't act as fuel.
____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):
0.0.2

#### Your most recent log file where the issue was present: 

[pastebin/gist/pastee etc link here]

**Comment by ct-klein** [comment]
Also has the same effect with the 'Reaction generator' which requires nuclearcraft specific fuel (uranium/thorium) The machine is a 100rf/t generator and worst case could probably be removed if the issue with the fuel types cannot be resolved.

**Comment by JasonMcRay** [comment]
Swapped the unification to NuclearCraft Uranium and Thorium.
