### ISSUE TITLE
Water is infinite like in Vanilla Minecraft

### ISSUE THREAD

**Issue by lafflam** [JasonMcRay/Infitech-2-reloaded#4]
What happens:
Water is infinite like in Vanilla Minecraft.

What you expected to happen:
Since water was not infinite in Infitech 2, I expected water to not be infinite in Infitech 2.5.

Modpack Version: Infitech 2 - Pre-loaded-0.0.1

I have not modified the pack in any way.

This issue is happening on the CLIENT in SINGLE PLAYER.
I have not tested this on server, but I assume water would be infinite on a server as well.

Log: N/A

**Comment by JasonMcRay** [comment]
It should be finite. Forgot about that one, thanks

**Comment by JasonMcRay** [comment]
Water will be infinite only in Ocean and Beach biomes.
