### ISSUE TITLE
duplicate recipe; wet coke oven brick

### ISSUE THREAD

**Issue by ct-klein** [JasonMcRay/Infitech-2-reloaded#5]
#### Issue Description:
Also please state if you modified the modpack in any way.
Duplicate recipe; railcraft vs immersive engineering coke oven brick

#### Is the issue happening on server? Client? Both?
only client testing

#### What happens:
wet coke oven brick.  usage receipe shows two things for smelting.  it makes a railcraft cokeoven brick and an immersive engineering coke brick.  When you actually do smelt it the railcraft coke oven brick comes out so you cannot make the immersive engineering coke oven

#### What you expected to happen:

According to Jason, it's an oversight.  rc coke oven is not supposed to be craftable.

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):
Pre-loaded-0.0.1

#### Your most recent log file where the issue was present: 

n/a

**Comment by JasonMcRay** [comment]
Removed RC Coke Oven
