### ISSUE TITLE
Iron ingot->nugget error

### ISSUE THREAD

**Issue by ct-klein** [JasonMcRay/Infitech-2-reloaded#9]
#### Issue Description:
Also please state if you modified the modpack in any way.
Duplicate/Incorrect recipe; Iron Ingot->Iron nugget

#### Is the issue happening on server? Client? Both?
client

#### What happens:
When you do shapeless crafting to convert an vanilla iron ingot into iron nuggets you get a tinkers construct iron nugget.  This cannot be converted into a wrought iron nugget.
The 'shapeless' recipe for an iron ingot shows it produces gregtech iron nuggets for both.

#### What you expected to happen:
Would expect a gt iron nugget

#### Steps to reproduce (if aplicable):

1.Iron ingot to crafting table or player craft shows tinkers nugget
2.
3.
...

____
#### Modpack Version (Do *not* use word "latest", use the numerical indication of the version):
0.0.1b

#### Your most recent log file where the issue was present: 
recipe error shows at bottom
https://pastebin.com/TUXRNDAp

**Comment by JasonMcRay** [comment]
Fixed in 0.0.2
